### ISSUE TITLE
Tokens in inline IL signatures not mapped to new assembly

### ISSUE THREAD

**Issue by toptensoftware** [Lokad/ILPack#106]
Inline signatures might contain tokens that need to be converted to tokens for the new assembly's metadata.

https://github.com/Lokad/ILPack/blob/610c6acadec63b9c5058d1fb01052d187d841066/src/IL/MethodBodyWriter.cs#L87

**Comment by toptensoftware** [comment]
btw: I wouldn't stress too much about this.  The only instruction that uses this is `calli` and trying to find examples of it in netcore is really difficult.  I just did a ildasm/grep across the entire netcore system dlls directory and couldn't find a single example.  Windows .NET framework on the other hand has many instances of it.

Also, Roslyn doesn't appear to use `Calli` at all:

https://source.roslyn.codeplex.com/#System.Reflection.Metadata/System/Reflection/Metadata/IL/ILOpCode.cs,6929573abac8b4ca,references

Compared to `Call` which it does:

https://source.roslyn.codeplex.com/#System.Reflection.Metadata/System/Reflection/Metadata/IL/ILOpCode.cs,afdbfd5012ccde5c,references

**Comment by OlegRa** [comment]
@vermorel Can we postpone this issue for now? The `calli` OpCode is used now by Roslyn mostly for the native interop and we have to proceed with this case correctly (with rewriting the signature using proper arguments' types tokens) but it's not as easy as I've thought before.

**Comment by vermorel** [comment]
@OlegRa No problem to postpone.
