### ISSUE TITLE
Non-public properties causing failure

### ISSUE THREAD

**Issue by VG9tIEhpY2tsaW5n** [Lokad/ILPack#108]
https://github.com/Lokad/ILPack/blob/8c3ede09651748784488e9d1c1e56471731cddd0/src/AssemblyGenerator.Properties.cs#L21

`PropertyInfo.GetGetMethod()` and `PropertyInfo.GetSetMethod()` do not return non-public accessors, so for properties that were generated without a public accessor this line causes a failure. Changing this line to the below fixed my use case, would you mind incorporating that into the source? Thanks.
```var eitherAccessor = propertyInfo.GetMethod ?? propertyInfo.SetMethod;```

**Comment by vermorel** [comment]
Thanks a lot! The version `0.1.1.0` now includes this fix.
