### ISSUE TITLE
Property attributes are not serialized

### ISSUE THREAD

**Issue by sam80180** [Lokad/ILPack#114]
As the title says,
only class attributes are serialized.

**Comment by vermorel** [comment]
Thanks for reporting this! Pull requests are welcome. We will try to fix this in the future, but as it's not critical for our own usage, it can promise yet at date.

**Comment by OlegRa** [comment]
@vermorel In fact this issue was properly fixed in PR #115 with appropriate unit tests so it can be safely closed.
