### ISSUE TITLE
peverify fails on emitted assemblies with file not found error

### ISSUE THREAD

**Issue by AArnott** [Lokad/ILPack#131]
After emitting a fairly trivial assembly using ILPack, running peverify.dll on that assembly produces this output:

```
peverify D:\git\MessagePack-CSharp\bin\DynamicCodeDumper\Debug\net5.0\DynamicObjectResolver.dll

Copyright (c) Microsoft Corporation.  All rights reserved.

 [HRESULT 0x80070002] - The system cannot find the file specified.

1 Error(s) Verifying D:\git\MessagePack-CSharp\bin\DynamicCodeDumper\Debug\net5.0\DynamicObjectResolver.dll
```

In contrast, running peverify.dll on the exact same dynamic assembly except written out by `AssemblyBuilder.Save`, peverify succeeds:

```
peverify "D:\git\MessagePack-CSharp\bin\DynamicCodeDumper\Debug\net472\MessagePack.Resolvers.DynamicObjectResolver.dll"

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

All Classes and Methods in D:\git\MessagePack-CSharp\bin\DynamicCodeDumper\Debug\net472\MessagePack.Resolvers.DynamicObjectResolver.dll Verified.
```

**Comment by vermorel** [comment]
@AArnott Thanks for reporting this! The biggest challenge we face with ILPack is to make those issues minimally reproducible. I have merged your previous PR (great work!). I don't have the resources to aggressively chase those problems, but I will try to keep up with the PR requests if any.

**Comment by AArnott** [comment]
@ericstj investigated my report and shared on another thread that the problem isn't ILPack, but rather that peverify isn't the right tool to use on a .NET Core assembly. Instead, one should use [ILVerify](https://github.com/dotnet/runtime/blob/739c53e737e25a47df3d75e39d167463e6da0688/src/coreclr/src/tools/ILVerify/README.md). This reported a passing grade on the ILPack generated assembly. :)
