### ISSUE TITLE
(with patch)

### ISSUE THREAD

**Issue by mf-RDP** [Lokad/ILPack#132]
Hi,

attached a patch for a little issue in AssemblyMetadata.cs ("HACK: [vermorel] 2019-07-25."). 

It will attach a ref to "netstandard" and make sure the ref to the assemblyname "system.private.corelib" is as per loaded in application current domain. 

I noticed problems when AOTing with Mono (system.private.corelib not found) and ILSpy couldn't resolve these references either. With this patch, problems are gone.

I cannot say 100% sure if it will work for all NET versions, tested with netcore31, net50, mono. All ok-

[0001-patch-for-reference-assemblies-netstandard-unresolve.zip](https://github.com/Lokad/ILPack/files/5649590/0001-patch-for-reference-assemblies-netstandard-unresolve.zip)

Best regards,
S.

**Comment by vermorel** [comment]
Thanks for the patch. It's preferable to use the _pull requests_, it's easier to edit, and it's also easier to assign proper attribution.
