### ISSUE TITLE
(with patch) Functions with 'void*' in params list

### ISSUE THREAD

**Issue by mf-RDP** [Lokad/ILPack#137]
Hi Lokad,

sorry for not providing a PR yet.
Provided attached patch will fix not being able to write calls to functions with 'void*' ptrs in signature / params.

Many Thanks again for this lib :) :)

Sascha (mf-RDP)

[0001-Fix-for-calls-to-functions-with-param-type-void.zip](https://github.com/Lokad/ILPack/files/6042519/0001-Fix-for-calls-to-functions-with-param-type-void.zip)

**Comment by vermorel** [comment]
Thanks a lot! Would you be able to add a matching example in the `TestSubject` assembly? I strongly prefer to have fixes assorted with an automated test of some kind.

**Comment by mf-RDP** [comment]
So this should be the desired test.
[0001-call-func-void-.-test.patch.zip](https://github.com/Lokad/ILPack/files/6044969/0001-call-func-void-.-test.patch.zip)

**Comment by mf-RDP** [comment]
I have a remark addressing something else:
In AssemblyMetadata.Methods.cs, Line 57 + 58 you wrote:

                // TODO: What about generic method definitions in a generic type???
                //System.Diagnostics.Debug.Assert(!methodBase.IsGenericMethod);

I am under the impression (but don't know for sure), this check can be removed for generic methods in generic types.
At least for me, I instanced both (type and method) to <object> in the below example and the generated code looked fine in ILSpy.

`.method public static 
	void ContinueWith13 (
		class [CORE]anet_CORE.execution_context ''
	) cil managed 
{
	.param [1] = nullref
	// Method begins at RVA 0x57e28
	// Code size 18 (0x12)
	.maxstack 8

	IL_0000: ldarg.0
	IL_0001: call object [CORE]anet_CORE.JTC::pop_obj(class [CORE]anet_CORE.execution_context)
	IL_0006: ldarg.0
	IL_0007: call object [CORE]anet_CORE.JTC::pop_obj(class [CORE]anet_CORE.execution_context)
	IL_000c: call instance class [System.Private.CoreLib]System.Threading.Tasks.Task`1<!!0> class [System.Private.CoreLib]System.Threading.Tasks.Task`1<bool>::ContinueWith<object>(class [System.Private.CoreLib]System.Func`2<class [System.Private.CoreLib]System.Threading.Tasks.Task`1<!0>, !!0>)
	IL_0011: ret
} // end of method SemaphoreSlim_TaskNode::ContinueWith13
`

**Comment by vermorel** [comment]
Thanks @mf-RDP! I have merged the change. Let me know if you need me to update the Nuget package.
