### ISSUE TITLE
(with proposed patch), null dereference in TryGetRawMetadata after removed null check

### ISSUE THREAD

**Issue by mf-RDP** [Lokad/ILPack#138]
Hi Vermorel,

I have to propose the following diff/patch. I noticed in TryGetRawMetadata there was a null check on 'pi', which has been removed lately (last few days), what causes problems: RuntimeAssembly.GetRawBytes is not present for me, at least not when working on netstandard2.0.

In order to avoid the null deref, we just can 'return false' or apply the proposed attached patch. Proposed only because I just guess that reading the assembly file is the same than what GetRawBytes would do.

Kindest Regards,
Sascha (mf-RDP).

![image](https://user-images.githubusercontent.com/48090523/111068370-c77b3c00-84c8-11eb-96fa-0a245e49bdc7.png)

[0001-fixes-null-dereference-of-pi-resulting-in-unhandled-.zip](https://github.com/Lokad/ILPack/files/6136650/0001-fixes-null-dereference-of-pi-resulting-in-unhandled-.zip)

**Comment by vermorel** [comment]
Patch file has been merged. Thanks!
