### ISSUE TITLE
Saved Dynamic Assembly Not showing in VS intellisense but ILSpy and VS Object Explorer Look correct

### ISSUE THREAD

**Issue by mvbordogna** [Lokad/ILPack#147]
So my package is built using the Reflection.Emit, All looks good, unless i am missing something in ways of type attribute directives that will allow the saved dll from ILPack to be referenced at Compile time. 
So after making a references to the new saved assembly, I add a reference to it in a project that will be compiled, but when i try to reference it starting with the fqtn aka the namespace, but nothing. the name space isn't in the intellisense drop down. 

Is this a limitation of the save from ILPack or is this a limitation of dynamically generated assemblies in general.

if not the latter, what would the adjustments to ILPack look like, i would be happy to help out with a PR if someone can point me in the right direction on this.

**Comment by vermorel** [comment]
Thanks for the interest and feedback. This is appreciated. I would suspect that ILPack isn't including some tidbits which not needed to run the logic, but needed by the tooling on top of it. I don't have resources to put on the case. I am not even sure what sort of guidance I could provide beyond trying to replicate the problem with a minimalistic stand-alone case. Sorry for not being more helpful.

**Comment by mvbordogna** [comment]
Hi Vermoral, 
thanks for the quick response.... after looking at this for days.... and finally deciding to post, i figured out the issue....  I had a namespace collision and vs was lost.  However i changed the root of the namespace and all is showing now. going to close this with a comment. thank you for your help.
