### ISSUE TITLE
Type names containing special characters

### ISSUE THREAD

**Issue by osen1** [Lokad/ILPack#154]
We occasionally have Type names that contain a "+". Let's say for example "A+B". Such types are internally represented as "A\\+B", according to https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/specifying-fully-qualified-type-names#specify-special-characters
If I save such a type with .Net Framework's AssemblyBuilder.Save, it will be saved as "A+B". However, ILPack saves it as "A\u005cB".
-> Is a treatment of escaped special characters missing in ILPack?

**Comment by vermorel** [comment]
@osen1 You are correct. Escaped special characters are not handled by ILPack. Nice catch!

**Comment by osen1** [comment]
Thanks. I submitted a pull request.
