### ISSUE TITLE
DeclareInterfacesAndCreateInterfaceMap conundrum

### ISSUE THREAD

**Issue by dmiller** [Lokad/ILPack#164]
In `AssemblyGenerator.DeclareInterfacesAndCreateInterfaceMap`, one finds the code

```C#
MethodInfo targetMethod = ifcm.TargetMethods[i];
MethodInfo ifcMethod = ifcm.InterfaceMethods[i];

// Declare a method override either when the interface implementation or
// the interface method implementation is declared by the type.
if (implementedByType || targetMethod.DeclaringType.Equals(type))
    _metadata.Builder.AddMethodImplementation(
        (TypeDefinitionHandle)_metadata.GetTypeHandle(targetMethod.DeclaringType),
        _metadata.GetMethodHandle(targetMethod, false),
        _metadata.GetMethodHandle(ifcMethod, false));
```

It is possible for `targetMethod` to be `null`, leading to a `NullReferenceException`.  The case I ran into that causes this involves the situation with an interface `IA` with method `ma`, an interface `IB` derived from `IA` with method `mb`, and an abstract class `CA` which implements `IB` but does not supply a method for `ma`.  (There may be a simpler example, but this is what I had going on.)  Note that code like this will not compile in C# -- the compiler issues an error for the missing method `ma` -- but it can be created by direct IL generation.

Two fixes come to mind:  (1) Check `targetMethod` and avoid executing the `if` if it is `null`; or (2) Check `targetMethod` and throw an exception if it is `null`.

I do not know which is the correct behavior.  It is an error in C#, but not necessarily in the CIL spec.  None of PEVerify, ildasm, and ILSpy have a problem with it, `AssemblyBuilder.Save()` under Framework has no problem writing it to file, and `Assembly.Load()` has no problem loading that file.  (Which is why this situation has been occurring in my code for 12 years without being noticed.)

My own preference is to go with option (1) as a solution.  (Selfishly, so I don't have to figure out how to rewrite my own code; less selfishly, for consistency with the other tools.)  However, if it is the case that this situation is forbidden by the CIL spec, then (2) would be a better choice (and I should clean up my act).

I leave it to others to ponder.

**Comment by OlegRa** [comment]
In fact, static code analysis tools point to this problem correctly and suggest rewriting this `if` condition in a more safe way. I don't know how to write tests (maybe @dmiller can help with it) for this case but I've prepared PR #165 which makes processing logic clearer and safer.

**Comment by vermorel** [comment]
@dmiller Let us know if the last commit provided by @OlegRa helps.

**Comment by dmiller** [comment]
Close, but not quite.  In my example, `implementedByType` is true and `targetMethod` is `null`, so the guard passes but the dereferencing of `targetMethod` in the call to `AddMethodImplentation` blows up.

One solution: make the guard
```
if (targetMethod != null && (implementedByType || targetMethod.DeclaringType == type)) 
   ...
```
I can clean up my test case to a minimal example and drop a file here.  It's some straight IL gen and  a call to GenerateAssembly.  I can set it up so that it returns true if no exception and false on exception.  I don't know how you would want to incorporate that into your test suite -- it would not be in the mode of the tests I'm seeing in place now.

**Comment by dmiller** [comment]
[test.cs.txt](https://github.com/Lokad/ILPack/files/8730403/test.cs.txt)

`BuildNullTargetMethodExample`  throws an exception on current code, executes to completion with my suggested fix.

`TestNullTargetMethod` returns `false` and `true` instead.

Take your pick.

**Comment by OlegRa** [comment]
@dmiller Thanks a lot for test case. I'll prepare the new PR with fix and this new test combined.

**Comment by dmiller** [comment]
Thanks for the fast response.  I'm very glad to see all the activity on this project in recent weeks.  The recent fixes have solved all the problems I ran into several years back.  ILPack now seems able to handle all the code I'm tossing at it.

**Comment by dmiller** [comment]
This change fixes.  Exception no longer generated here.

(I'm now getting a BadImageFormatException from some new place.  I'll be back. :) )
