### ISSUE TITLE
API needs to be reviewed

### ISSUE THREAD

**Issue by osman-turan** [Lokad/ILPack#24]
Current API is misleading. Suppose a developer needs to integrate `ILPack` into a project. Since, generator methods (`AssemblyGenerator.GenerateAssemblyBytes` and `AssemblyGenerator.GenerateAssembly`) are instance methods, the developer might assume `AssemblyGenerator` does some caching between each generator method calls. So, he probably creates a single instance and use it to maximize efficiency. Also, he need to deal with `IDisposable` pattern for his single instance.

In contrast to above story, let's have a look at the facts:
- `AssemblyGenerator` does not cache anything (or at least currently).
- `IDisposable` implementation is purely redundant. It's there to dispose a-never-used `MemoryStream` which was created in constructor.
- A single instance won't work. Because, all fields which are shared between internal methods are never cleared. Meaning that all types, methods, fields etc. are cumulatively collected between each generator method calls.

So, I suggest to refactor current API or create a clean API from scratch. My suggestions are:
- Remove `IDisposable` and unused `MemoryStream`.
- Implement clearing logic between generator method calls and document somewhere about generator method calls are not thread safe for a single instance.
- Don't expose a static method for generating assemblies. Stick to instance class. We will probably need to cache some variables between generator method calls (like core runtime types to core library mapping tables).

**Comment by Twinside** [comment]
The current behavior of the Save() method in net462 makes impossible to continue adding types to the dumped dynamic assembly, so we use it only in debug scenario where any caching is not a concern.
