### ISSUE TITLE
System.ArgumentNullException on parameter.Name for property setter method

### ISSUE THREAD

**Issue by Cular** [Lokad/ILPack#25]
Hello. Recently I've tried to test your implementation of assembly saving logic and found little issue.
When I try to save my type, that works in runtime, I get an exception on saving setter method of my type. Example of my code [here](https://github.com/Cular/AssemblySaver_Test_ILPack). Maybe I've missed something on generation steps of my type. I'm totaly new in this features. :)

`parameterDef = _metadataBuilder.AddParameter(parameter.Attributes,GetString(parameter.Name),i);`

![image](https://user-images.githubusercontent.com/26927442/54273504-b1aba700-458e-11e9-9e61-e307f2c17520.png)

**Comment by osman-turan** [comment]
Thank you for the example repo. Much appreciated. I'll let you know when we have something (fix, workaround etc.) to share with you.

**Comment by osman-turan** [comment]
@Cular Could you try again with the latest changes, please?

**Comment by Cular** [comment]
@osman-turan, hello! Unfortunately, I'm not having an opportunity for testing this closes couple weeks. But I will little bit later. I think, you can close the issue for now. If I find any problems, than I will write here.

**Comment by vermorel** [comment]
I believe that this issue has been fixed, as we have now test cases covering this specific issue (see `MyClass.Properties.cs`). Thanks a lot for your early report though!
