### ISSUE TITLE
report about some case lost 

### ISSUE THREAD

**Issue by caozhiyuan** [Lokad/ILPack#28]
1. type have no namespace  
GetString(type.Namespace) will error
2. type Reference each other 
foreach GetOrCreateType(type)  and https://github.com/Lokad/ILPack/blob/master/src/IL/MethodBodyWriter.cs#L104 typeHandles[type.GUID] no key error.

**Comment by osman-turan** [comment]
This is probably related to #22. I'm working on it.

**Comment by osman-turan** [comment]
@caozhiyuan It should be fixed now. Could you test it, please?

**Comment by caozhiyuan** [comment]
1、type.Namespace get null (no Namespace class) will raise  error
2、AnonymousType will raise error
3、can test output netcore System.Net.Http.dll ?

**Comment by osman-turan** [comment]
@caozhiyuan Thank you for providing good indicators. Now, null strings are supported via #35 (and merged into master). Anonymous types have no namespace as well. So, it should cover your case.

**Comment by caozhiyuan** [comment]
can test output netcore System.Net.Http.dll ? @osman-turan   AnonymousType will raise error
