### ISSUE TITLE
Publish a NuGet package

### ISSUE THREAD

**Issue by TechInterMezzo** [Lokad/ILPack#29]
This is a great library to fill the gap of assembly serialization.

Are there any plans to publish it on NuGet?

**Comment by vermorel** [comment]
Yes, we will be publishing a NuGet package. We are not done yet, still ironing out bugs, but it's planned.

**Comment by vermorel** [comment]
Done at https://www.nuget.org/packages/Lokad.ILPack

Caveat:  the version 0.1 still has pending issues.
