### ISSUE TITLE
Fix user string handling 

### ISSUE THREAD

**Issue by osman-turan** [Lokad/ILPack#30]
`OperandType.InlineString` requires user string metadata token which is allocated by `GetOrAddUserString` (`#US` in .NET metadata). Current implementation use strings in `#Strings` heap which is allocated by `GetOrAddString`.

**Comment by osman-turan** [comment]
Added a unit test for it and fixed in #31.

**Comment by vermorel** [comment]
Should we close this issue? Thanks!

**Comment by osman-turan** [comment]
It's implemented with a unit test and we haven't received any bug report about it yet. So, I suppose we can safely close it.
