### ISSUE TITLE
Pull Request Process

### ISSUE THREAD

**Issue by toptensoftware** [Lokad/ILPack#80]
Hi @vermorel,

With the recent pull requests I've been sending I've been trying to keep them narrowly targeted but I realize this is probably causing some merge issues (especially with the unit tests). I just wanted to check if you prefer things less targeted or if there's anything else that'd make the process smoother.

One thing I was thinking is the tests would merge better if they weren't all in one file. After you've merged the current set of PRs I'll split things up into partial classes which should help in future.

Also... is logging an issue the best way to discuss stuff like this?

Brad

**Comment by vermorel** [comment]
@toptensoftware Your commits are highly professional, and of great value for this project. I am impressed :-). Small commits are ideal for the maintainer. Your suggestion of splitting unit tests into multiple files is good idea. Thanks again! I don't mind using the GitHub issues as a discussion board.
