### ISSUE TITLE
Missing method override

### ISSUE THREAD

**Issue by vermorel** [Lokad/ILPack#85]
Based on #84, it seems that we are not emitting the IL that encodes the overriding behavior of a method.

**Comment by osman-turan** [comment]
@vermorel I observed interface implementation are handled with current codebase and ILDASM shows `.override` keyword in generated assemblies. Relevant parts:

https://github.com/Lokad/ILPack/blob/427f21597f881b84a63207a9fd8b7fcefbb7ffcb/src/AssemblyGenerator.Methods.cs#L48-L73

**Comment by toptensoftware** [comment]
I put this in to get explicit interface method implementations working.  I did a couple of quick tests with the C# compiler and abstract/virtual methods and didn't see the .override directive.  I didn't test method overrides though as figured I'd get back to it at a later date.

**Comment by osman-turan** [comment]
@toptensoftware Yes, I confirm that `.override` is only generated for interface implementations. Abstract/virtual methods do not cause to generate `.override`.

**Comment by toptensoftware** [comment]
Test cases for this in PR #90.  I also checked the ildasm, and couldn't see C# compiler generating .overrides for any of these.

**Comment by vermorel** [comment]
Excellent!
